stages:
  - Quality
  - Publish
before_install:
  -   curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
install:
  - poetry install
jobs:
  include:
    - stage: Quality
      name: tests
      script: python -m unittest -b
    - stage: Publish
      script: skip
      before_deploy:
        - poetry build
        - poetry config repositories.testpypi https://test.pypi.org/simple/
        - poetry config http-basic.testpypi $key
      deploy:
        provider: script
        script: poetry publish -r testpypi`
